server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: com.kharkiv.movienight
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/movie_night
    username: postgres
    password: root
  liquibase:
    change-log: classpath:db.changelog/changelog-master.xml
user:
  oauth:
    clientId: R2dpxQ3vPrtfgF72
    clientSecret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
    redirectUris: https://www.postman.com/oauth2/callback,http://localhost:8081/auth/webjars/springfox-swagger-ui/oauth2-redirect.html
