server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: authorization-server
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth_db
    data-username: postgres
    data-password: root

user:
  oauth:
    clientId: R2dpxQ3vPrtfgF72
    clientSecret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
    redirectUris: http://localhost:8082/login/oauth2/code/,https://www.postman.com/oauth2/callback

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

